from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import numpy as np


@dataclass
class RunContext:
    """Everything a set of checks needs to know about a run.

    Engine adapters populate this. MD-oriented fields are first-class; a future
    non-MD domain (fluids, N-body) populates `extra` with its own observables
    and ships domain-specific checks that read from `extra`."""
    run_dir: Path
    engine: str
    selection: str
    positions: np.ndarray | None = None
    reference: np.ndarray | None = None
    atom_names: list[str] | None = None
    ca_positions: np.ndarray | None = None
    ca_reference: np.ndarray | None = None
    ca_labels: list[str] | None = None
    energy: np.ndarray | None = None
    structure_path: Path | None = None
    tpr_path: Path | None = None
    trajectory_path: Path | None = None
    system_atom_types: list[str] | None = None
    ff_param_types: list[str] | None = None
    params: dict[str, Any] | None = None
    metadata: dict[str, Any] = field(default_factory=dict)
    run_params: dict[str, Any] = field(default_factory=dict)
    skipped: dict[str, str] = field(default_factory=dict)
    extra: dict[str, Any] = field(default_factory=dict)
    # Every input file actually consumed while loading this run; the
    # provenance manifest hashes all of them (audit IO-001).
    consumed_inputs: list[Path] = field(default_factory=list)


def _find(run: Path, *patterns: str):
    from simval._util import find_files
    return find_files(run, *patterns)


def _find_unique(run: Path, *patterns: str, what: str = "input"):
    from simval._util import find_unique
    return find_unique(run, *patterns, what=what)


class EngineAdapter:
    """Port for domain/engine expansion. A new physics domain implements this:
    `detect` recognizes its run-dirs; `load_context` reads its outputs into a
    RunContext that checks then operate on."""
    name = "base"

    def detect(self, run: Path) -> bool:
        raise NotImplementedError

    def load_context(self, run: Path, selection: str) -> RunContext:
        raise NotImplementedError


class SyntheticEngine(EngineAdapter):
    name = "synthetic"

    #: Precise fixture signature (audit ENG-001): the synthetic corpus is
    #: generated by fixtures.make_run_dir and always carries exactly this
    #: npy triple. A bare "any *.npy" heuristic swallowed concrete domains
    #: (a wave run with a stray energy.npy diagnosed as synthetic).
    _SIGNATURE = ("energy.npy", "positions.npy", "reference.npy")

    def detect(self, run: Path) -> bool:
        return all((run / f).is_file() for f in self._SIGNATURE)

    def load_context(self, run: Path, selection: str) -> RunContext:
        ctx = RunContext(run_dir=run, engine=self.name, selection=selection)

        e = _find_unique(run, "energy.npy", what="energy series")
        if e is not None:
            ctx.energy = np.load(e)
            ctx.run_params["n_energy_samples"] = int(ctx.energy.size)
            ctx.consumed_inputs.append(e)

        pos = _find_unique(run, "positions.npy", what="positions trajectory")
        ref = _find_unique(run, "reference.npy", what="reference positions")
        if pos is not None and ref is not None:
            ctx.positions = np.load(pos)
            ctx.reference = np.load(ref)
            ctx.run_params["n_frames"] = int(ctx.positions.shape[0])
            ctx.run_params["n_atoms"] = int(ctx.positions.shape[1])
            ctx.consumed_inputs += [pos, ref]

        sys_atoms_p = run / "atom_types.txt"
        ff_p = run / "ff_atom_types.txt"
        if sys_atoms_p.exists() and ff_p.exists():
            ctx.system_atom_types = [line.strip() for line in sys_atoms_p.read_text().splitlines() if line.strip()]
            ctx.ff_param_types = [line.strip() for line in ff_p.read_text().splitlines() if line.strip()]
            ctx.run_params["n_system_atom_types"] = len(set(ctx.system_atom_types))
            ctx.consumed_inputs += [sys_atoms_p, ff_p]

        params_path = run / "params.json"
        if params_path.exists():
            from simval.units import Quantity
            raw = json.loads(params_path.read_text())
            ctx.params = {k: Quantity(v["value"], v["unit"]) for k, v in raw.items()}
            ctx.consumed_inputs.append(params_path)
        return ctx


class GromacsEngine(EngineAdapter):
    name = "gromacs"

    def detect(self, run: Path) -> bool:
        return bool(_find(run, "*.xtc", "*.dcd", "*.trr", "*.nc"))

    def load_context(self, run: Path, selection: str) -> RunContext:
        from simval import io, metadata as meta_mod
        from simval._util import (
            gromacs_scenario_inputs,
            select_run_topology,
            select_structure,
            select_trajectory_topology,
        )
        from simval.units import Quantity

        ctx = RunContext(run_dir=run, engine=self.name, selection=selection)
        ctx.run_params["engine"] = "gromacs"
        ctx.run_params["selection"] = selection

        # Provenance consumes the canonical scenario enumeration (audit
        # ORA-005): every PRESENT role is hashed, regardless of whether an
        # optional extraction over it later succeeded (audit PROV-002).
        ctx.consumed_inputs = gromacs_scenario_inputs(run)

        # MD inputs are ROLES, not mutually-exclusive alternatives: a normal
        # run-dir carries a structure (.gro/.pdb), a run topology (.tpr) and
        # a trajectory. Only multiple candidates for the SAME role are
        # ambiguous; the trajectory-topology precedence is documented in
        # simval._util (audit GROM-001).
        top = select_trajectory_topology(run)
        xtc = _find_unique(run, "*.xtc", "*.dcd", "*.trr", "*.nc", what="trajectory")
        ctx.trajectory_path = xtc
        if top and xtc:
            ctx.positions, ctx.reference, ctx.atom_names = io.load_trajectory(xtc, top, selection=selection)
            ctx.run_params["n_frames"] = int(ctx.positions.shape[0])
            ctx.run_params["n_selected_atoms"] = int(ctx.positions.shape[1])
            try:
                ctx.ca_positions, ctx.ca_reference, _ = io.load_trajectory(
                    xtc, top, selection="protein and name CA")
                ctx.ca_labels = io.load_residue_labels(top)
            except (ImportError, ModuleNotFoundError) as e:
                ctx.skipped["ca_positions"] = f"optional dependency unavailable: {e}"[:160]
            except ValueError as e:
                # No CA atoms / selection not applicable to this topology:
                # explicitly not-applicable, recorded as a skip.
                ctx.skipped["ca_positions"] = f"CA selection not applicable: {e}"[:160]
            except Exception as e:
                # Unexpected failure of an applicable load: surfaced to the
                # pipeline as a failing per_residue_rmsf error (PIPE-001).
                ctx.extra["ca_load_error"] = f"{type(e).__name__}: {e}"[:200]

        ctx.tpr_path = select_run_topology(run)
        if ctx.tpr_path is not None:
            try:
                types = io.load_atom_types(ctx.tpr_path, selection=selection)
            except Exception as e:
                # An unexpected topology parse failure must surface as a
                # failing ff_coverage diagnostic when the check is
                # applicable, never silently disable it (audit FF-001).
                # (A typed not-available returns [] instead of raising.)
                ctx.extra["ff_load_error"] = f"{type(e).__name__}: {e}"[:200]
            else:
                ctx.system_atom_types = types or None
                if ctx.system_atom_types:
                    ctx.run_params["n_system_atom_types"] = len(set(ctx.system_atom_types))

        ff_p = run / "ff_atom_types.txt"
        if ff_p.exists():
            ctx.ff_param_types = [line.strip() for line in ff_p.read_text().splitlines() if line.strip()]
            ctx.consumed_inputs.append(ff_p)

        ctx.structure_path = select_structure(run)

        xvg = _find_unique(run, "*.xvg", what="energy file (xvg)")
        if xvg is not None:
            try:
                term, arr = io.load_preferred_energy(xvg)
            except io.ConservedEnergyColumnMissing as e:
                # A well-formed file with no labeled conserved-energy
                # column: the energy check is explicitly not applicable,
                # never silently run on an arbitrary positional column
                # (audit IO-002). This is the ONLY typed skip (IO-003).
                ctx.skipped["energy"] = str(e)[:160]
            except Exception as e:
                # Malformed data (non-numeric row, ragged table) must
                # surface as a failing energy_drift diagnostic, never a
                # skip (audit IO-003).
                ctx.extra["energy_load_error"] = f"{type(e).__name__}: {e}"[:200]
            else:
                ctx.energy = arr
                ctx.run_params["energy_term"] = term
                ctx.run_params["n_energy_samples"] = int(ctx.energy.size)

        params_path = run / "params.json"
        if params_path.exists():
            raw = json.loads(params_path.read_text())
            ctx.params = {k: Quantity(v["value"], v["unit"]) for k, v in raw.items()}
            ctx.run_params["params"] = raw

        mdp = _find_unique(run, "mdout.mdp", "*.mdp", what="run parameters (mdp)")
        top_top = _find_unique(run, "*.top", what="topology file (top)")
        methods_file = run / "methods.json"
        if methods_file.exists():
            md = __import__("json").loads(methods_file.read_text())
            ctx.metadata = md
            ctx.run_params["force_field"] = md.get("force_field")
            ctx.run_params["water_model"] = md.get("water")
        else:
            meta = meta_mod.build_metadata(mdp, top_top, gmx_version=_gmx_version())
            ctx.metadata = meta
            ctx.run_params["force_field"] = meta["force_field"]
            ctx.run_params["water_model"] = meta["water_model"]
            ctx.metadata["methods"] = meta_mod.render_methods(meta)
        return ctx


def _gmx_version() -> str | None:
    import subprocess
    try:
        out = subprocess.run(["gmx", "--version"], capture_output=True, text=True, timeout=10)
        for ln in out.stdout.splitlines():
            if ln.strip().startswith("GROMACS version:"):
                return ln.split(":", 1)[1].strip()
    except Exception:
        return None
    return None


_ENGINES: list[EngineAdapter] = [GromacsEngine(), SyntheticEngine()]
_optional_engines_loaded = False


def _load_optional_engines() -> None:
    global _optional_engines_loaded
    if _optional_engines_loaded:
        return
    _optional_engines_loaded = True
    try:
        import simval.nbody  # noqa: F401  (registers ReboundEngine if rebound installed)
    except Exception:
        pass
    try:
        import simval.wave  # noqa: F401  (registers WaveEngine; numpy-only)
    except Exception:
        pass
    try:
        import simval.fluid  # noqa: F401  (registers FluidEngine; numpy-only)
    except Exception:
        pass
    try:
        import simval.em  # noqa: F401  (registers EMEngine; numpy-only)
    except Exception:
        pass
    try:
        import simval.quantum  # noqa: F401  (registers QuantumEngine; numpy-only)
    except Exception:
        pass
    try:
        import simval.fep  # noqa: F401  (registers FepEngine; needs alchemlyb/pymbar)
    except Exception:
        pass
    try:
        import simval.pyscf_eng  # noqa: F401  (registers PyscfEngine; needs pyscf)
    except Exception:
        pass
    try:
        import simval.qiskit_eng  # noqa: F401  (registers QiskitEngine; needs qiskit)
    except Exception:
        pass
    try:
        import simval.ontos_eng  # noqa: F401  (registers OntosEngine; reference is stdlib-only)
    except Exception:
        pass
    try:
        import simval.kinetics  # noqa: F401  (numpy-only)
    except Exception:
        pass
    try:
        import simval.diffusion  # noqa: F401  (numpy-only)
    except Exception:
        pass
    try:
        import simval.relativistic  # noqa: F401  (numpy-only)
    except Exception:
        pass


def register_engine(adapter: EngineAdapter) -> None:
    _ENGINES.append(adapter)


def select_engine(run: Path) -> EngineAdapter:
    """Evaluate EVERY detector and require exactly one match (audit ENG-001).

    First-match selection made detection order load-bearing: the synthetic
    engine (registered early, loosely keyed on *.npy) silently swallowed
    run-dirs of concrete domains that carried a stray npy file, skipping
    their domain checks and provenance. Ambiguity now fails closed, naming
    the candidates."""
    _load_optional_engines()
    matches = [eng for eng in _ENGINES if eng.detect(run)]
    if len(matches) == 1:
        return matches[0]
    names = sorted(eng.name for eng in matches)
    if not matches:
        raise ValueError(f"no engine recognized run-dir: {run}")
    raise ValueError(
        f"ambiguous run-dir {run}: engines {names} all match — a run-dir must "
        "identify exactly one domain (audit ENG-001)"
    )
